<div align="center" id="checkedout">
    <div class="sub-content">
        <?php
            if ($this->session->get('flash') == TRUE) {
                echo "<div class=\"alert alert-" . $this->session->get('flash_type') . " alert-dismissible\" role=\"alert\">";
                echo $this->flashSession->output();
                echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
                echo "<span aria-hidden=\"true\">&times;</span>";
                echo "</button></div>";
                $this->session->set('flash', FALSE);
                $this->session->set('flash_type', '');
            }
        ?>
        <h3><strong>Purchase Successful!</strong></h3>
        <br>
        Your order has been processed. Thank you for shopping with us.
        <br>
        <br>
        You can click the button below to see your order history.
        <br>
        <br>
    </div>
    <div class="text-center mx-auto">
    <button type="button" class="btn btn-dark text-center mx-auto"><?php echo $this->tag->linkTo(["users/orderhistory", "View my Order History", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
</div>
</div>