<div align="center" id="checkedout">
    <div class="sub-content">
        <strong>Purchase Successful!</strong>
        <br />
        <br />
        Your order has been processed. Thank you for shopping with us.
        <br />
        <br />
        You can click the button below to see your order history.
        <br />
        <br />
    </div>
    <div class="text-center mx-auto">
    <button type="button" class="btn btn-dark text-center mx-auto"><?php echo $this->tag->linkTo(["users/orderhistory", "View my Order History", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
</div>
</div>