<div class="page-header">
    <h1><strong>Playground List</strong></h1>
</div>

<br>

<div class="row">
<div class="border-dark col-md-3">
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Wonder Park</a>
  <a href="http://localhost:8000/playground/adultbumpercar" class="list-group-item list-group-item-action">Adult Bumper Car</a>
  <a href="http://localhost:8000/playground/carousel" class="list-group-item list-group-item-action">Carousel</a>
  <a href="http://localhost:8000/playground/caterpillar" class="list-group-item list-group-item-action">Caterpillar</a>
  <a href="http://localhost:8000/playground/ferriswheel" class="list-group-item list-group-item-action">Ferris Wheel</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Adventure Park</a>
  <a href="http://localhost:8000/playground/fourdcinema" class="list-group-item list-group-item-action">4D Cinema</a>
  <a class="list-group-item list-group-item-primary list-group-item-action"><strong>> F1 Supakart <</strong></a>
  <a href="http://localhost:8000/playground/ftwosupakart" class="list-group-item list-group-item-action">F2 Supakart</a>
  <a href="http://localhost:8000/playground/iceworldarctic" class="list-group-item list-group-item-action">Ice World Arctic</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Waterpark</a>
  <a href="http://localhost:8000/playground/waterpark" class="list-group-item list-group-item-action">Waterpark</a>
</div>
</div>

<div class="list-group-item list-group-item-primary text-dark col-md-9">
  <h2 class="text-center"><strong>F1 Supakart</strong></h2>
  <br>
  <img class="mx-auto d-block" src="/img/index/f1supakart.jpg" alt="f1supakart.jpg" width="50%" height="50%">
  <br>
  <h5 class="text-center">Ready, get set and go! Race around the racetrack and feel just like an F1 driver would as you race through our racetrack designed by professional racers to simulate the sharp turns and curves at top speed.</h5>
  <br>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MAX WEIGHT:</strong> -</h5>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MIN HEIGHT:</strong> 150 CM</h5>
  <br>
</div>
<div>

<br><br>
