<div class="page-header">
    <h1><strong>Playground List</strong></h1>
</div>

<br>

<div class="row">
<div class="border-dark col-md-3">
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Wonder Park</a>
  <a href="http://localhost:8000/playground/adultbumpercar" class="list-group-item list-group-item-action">Adult Bumper Car</a>
  <a href="http://localhost:8000/playground/carousel" class="list-group-item list-group-item-action">Carousel</a>
  <a href="http://localhost:8000/playground/caterpillar" class="list-group-item list-group-item-action">Caterpillar</a>
  <a href="http://localhost:8000/playground/ferriswheel" class="list-group-item list-group-item-action">Ferris Wheel</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Adventure Park</a>
  <a class="list-group-item list-group-item-primary list-group-item-action"><strong>> 4D Cinema <</strong></a>
  <a href="http://localhost:8000/playground/fonesupakart" class="list-group-item list-group-item-action">F1 Supakart</a>
  <a href="http://localhost:8000/playground/ftwosupakart" class="list-group-item list-group-item-action">F2 Supakart</a>
  <a href="http://localhost:8000/playground/iceworldarctic" class="list-group-item list-group-item-action">Ice World Arctic</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Waterpark</a>
  <a href="http://localhost:8000/playground/waterpark" class="list-group-item list-group-item-action">Waterpark</a>
</div>
</div>

<div class="list-group-item list-group-item-primary text-dark col-md-9">
  <h2 class="text-center"><strong>4D Cinema</strong></h2>
  <br>
  <img class="mx-auto d-block" src="/img/index/4dcinema.jpg" alt="4dcinema.jpg" width="50%" height="50%">
  <br>
  <h5 class="text-center">Ride on our simulators with 3-D graphics and 360-degree surround sounds and multi-sensory special effects.</h5>
  <p></p>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MAX WEIGHT:</strong> 120 KG</h5>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MIN HEIGHT:</strong> 116 CM</h5>
  <p></p>
  <h5 class="text-center">Children below 122 CM needs adult accompaniment.</h5>
</div>
<div>

<br><br>
