<div class="page-header">
    <h1><strong>Playground List</strong></h1>
</div>

<br>

<div class="row">
<div class="border-dark col-md-3">
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Wonder Park</a>
  <a href="http://localhost:8000/playground/adultbumpercar" class="list-group-item list-group-item-action">Adult Bumper Car</a>
  <a href="http://localhost:8000/playground/carousel" class="list-group-item list-group-item-action">Carousel</a>
  <a href="http://localhost:8000/playground/caterpillar" class="list-group-item list-group-item-action">Caterpillar</a>
  <a href="http://localhost:8000/playground/ferriswheel" class="list-group-item list-group-item-action">Ferris Wheel</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Adventure Park</a>
  <a href="http://localhost:8000/playground/fourdcinema" class="list-group-item list-group-item-action">4D Cinema</a>
  <a href="http://localhost:8000/playground/fonesupakart" class="list-group-item list-group-item-action">F1 Supakart</a>
  <a href="http://localhost:8000/playground/ftwosupakart" class="list-group-item list-group-item-action">F2 Supakart</a>
  <a href="http://localhost:8000/playground/iceworldarctic" class="list-group-item list-group-item-action">F2 Ice World Arctic</a>
</div>
<br>
<div class="list-group text-center mx-auto">
  <a class="list-group-item list-group-item-dark">Waterpark</a>
  <a class="list-group-item list-group-item-primary list-group-item-action"><strong>> Waterpark <</strong></a>
</div>
</div>

<div class="list-group-item list-group-item-primary text-dark col-md-9">
  <h2 class="text-center"><strong>Waterpark</strong></h2>
  <br>
  <img class="mx-auto d-block" src="/img/index/waterpark.jpg" alt="waterpark.jpg" width="50%" height="50%">
  <p></p>
  <h5 class="text-center">And just when you thought you couldn’t possibly have any more fun, our very own WaterPark is the perfect way to end your day as sessions run from morning to night. It is every child’s dream come true as you watch them scream and play in endless delight while creating everlasting memories.</h5>
  <p></p>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MAX WEIGHT:</strong> -</h5>
  <h5 class="w-50 list-group-item mx-auto text-center"><strong>MIN HEIGHT:</strong> 90 CM</h5>
</div>
<div>

<br><br>
