<div align="center" id="fourohfour">
    <div class="sub-content">
        <strong>ERROR 404</strong>
        <br />
        <br />
        You have tried to access a page which does not exist or has been moved.
        <br />
        <br />
        Please click the links at the top navigation bar to 
        navigate to other parts of the site, or
        click the button below to get out of here.
        <br />
        <br />
    </div>
    <div class="text-center mx-auto">
    <button type="button" class="btn btn-dark text-center mx-auto"><?php echo $this->tag->linkTo(["", "TAKE ME HOME", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
    </div>
</div>