<img class="mx-auto d-block" src="/img/index/parkmap.png" alt="parkmap.png" width="100%" height="100%">

<br>

<div class="page-header">
    <h1><strong>Jerudong Park Map</strong></h1>
</div>

<br>

<h5>View Fullscreen Park Map: 
<a type="button" href="/img/index/parkmap.png" class="btn btn-dark">View Park Map</a>
</h5>

<hr>

<h5>Explore and get to know more of Jerudong Park:</h5>

<br>

<a type="button" href="http://localhost:8000/playground" class="btn btn-dark">View Playground Rides</a>

<br><br>

<a type="button" href="http://localhost:8000/foodcourt" class="btn btn-dark">View Food Court</a>

<br><br>

<a type="button" href="http://localhost:8000/contact" class="btn btn-dark">Get Directions to Jerudong Park</a>

<br><br>
