<?php echo $this->getContent() ?>

<?php
  if ($this->session->get('flash') == TRUE) {
    echo "<div class=\"alert alert-" . $this->session->get('flash_type') . " alert-dismissible\" role=\"alert\">";
    echo $this->flashSession->output();
    echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
    echo "<span aria-hidden=\"true\">&times;</span>";
    echo "</button></div>";
    $this->session->set('flash', FALSE);
    $this->session->set('flash_type', '');
  }
?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('user')->username); ?></h1>

<br>

<div class="list-group w-25 text-center mx-auto">
  <a href="http://localhost:8000/users/edit" class="list-group-item list-group-item-action">Edit credentials</a>
  <a href="http://localhost:8000/users/editpassword" class="list-group-item list-group-item-action">Change password</a>
  <a href="http://localhost:8000/users/orderhistory" class="list-group-item list-group-item-action">My order history</a>
  <a href="http://localhost:8000/users/delete" class="list-group-item list-group-item-action list-group-item-danger">Delete account</a>
</div>

<br><br><br>