<?php echo $this->getContent() ?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('username')); ?></h1>

<br>

<div class="list-group w-25 text-center mx-auto">
  <a href="http://localhost:8000/users/editusername" class="list-group-item list-group-item-action">Edit username</a>
  <a href="http://localhost:8000/users/editpassword" class="list-group-item list-group-item-action">Change password</a>
  <a href="#" class="list-group-item list-group-item-action">Set profile picture</a>
  <a href="http://localhost:8000/users/delete" class="list-group-item list-group-item-action list-group-item-danger">Delete account</a>
</div>

<br><br><br>