<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('user')->username); ?></h1>

<br>

<ul class="list-group w-50 text-center mx-auto">
  <li class="list-group-item list-group-item-danger">Your account will be permanently deleted. You will lose all items currently in your cart and your order history (if any). Are you sure?</li>
</ul>

<br>

<div class="text-center mx-auto">
    <a type="button" href="http://localhost:8000/users/deletesubmit" class="btn btn-danger">Yes, delete my account</a>
    <a type="button" href="http://localhost:8000/users/account" class="btn btn-dark">No, go back</a>
</div>

<br><br>
