<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('user')->username); ?></h1>

<br>

<ul class="list-group w-50 text-center mx-auto">
  <li class="list-group-item list-group-item-danger">Your account will be permanently deleted. You will lose all items currently in your cart and your order history (if any). Are you sure?</li>
</ul>

<br>

<div class="text-center mx-auto">
    <button type="button" class="btn btn-danger text-center mx-auto"><?php echo $this->tag->linkTo(["users/deletesubmit", "Yes, delete my account", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
    <button type="button" class="btn btn-dark text-center mx-auto"><?php echo $this->tag->linkTo(["users/account", "No, go back", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
</div>


<br><br>
