<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php
  if ($this->session->get('flash') == TRUE) {
    echo "<div class=\"alert alert-" . $this->session->get('flash_type') . " alert-dismissible\" role=\"alert\">";
    echo $this->flashSession->output();
    echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
    echo "<span aria-hidden=\"true\">&times;</span>";
    echo "</button></div>";
    $this->session->set('flash', FALSE);
    $this->session->set('flash_type', '');
  }
?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('user')->username); ?></h1>

<?php
    echo $this->tag->form(
        [
            "users/editpasswordsubmit",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<br>

<form>
  <div class="form-group w-50 text-center mx-auto">
    <label for="exampleInputPassword1">Please specify your new password</code>:</label>
    <input type="password" class="form-control" id="password" placeholder="Enter password here (at least 8 characters)" name="userPassword" required>
    <br>
    <button type="submit" class="btn btn-dark text-center mx-auto">Submit</button>
    <a type="button" href="http://localhost:8000/users/account" class="btn btn-danger text-center mx-auto">Cancel</a>
  </div>
</form>

<?php echo $this->tag->endForm(); ?>

<br><br>
