<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<img class="mx-auto d-block" src="/img/users/default.png" alt="user.png" width="20%" height="20%">

<br>

<h1 class="text-center"><?php echo htmlspecialchars($this->session->get('username')); ?></h1>

<?php
    echo $this->tag->form(
        [
            "users/editusernamesubmit",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<br>

<?php echo $this->getContent() ?>
<form>
  <div class="form-group w-50 text-center mx-auto">
    <label for="exampleInputUsername1">Please specify your new username:</label>
    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter username here" name="userName" value="<?php echo $this->request->getPost("userName")?>" required>
    <br>
    <button type="submit" class="btn btn-dark text-center mx-auto">Submit</button>
    <button type="button" class="btn btn-danger text-center mx-auto"><?php echo $this->tag->linkTo(["users/account", "Cancel", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
  </div>
</form>

<?php echo $this->tag->endForm(); ?>

<br><br>
