<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Login
    </h1>
</div>

<br>

<?php
  if ($this->session->get('flash') == TRUE) {
    echo "<div class=\"alert alert-" . $this->session->get('flash_type') . " alert-dismissible\" role=\"alert\">";
    echo $this->flashSession->output();
    echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
    echo "<span aria-hidden=\"true\">&times;</span>";
    echo "</button></div>";
    $this->session->set('flash', FALSE);
    $this->session->set('flash_type', '');
  }
?>

<?php
    echo $this->tag->form(
        [
            "session/start",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email" name="userEmail" value="<?php echo htmlspecialchars($this->request->getPost("userEmail", "email"))?>" required>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="password" placeholder="Password" name="userPassword" required>
  </div>
  <button type="submit" class="btn btn-dark">Submit</button>
</form>

<?php echo $this->tag->endForm(); ?>

<br><br>
<p>
  No account? <?php echo $this->tag->linkTo(["users/signup", "Sign up here."]) ?>
</p>
