<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Sign Up
    </h1>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<br>

<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="userEmail" value="<?php echo $this->request->getPost("userEmail", "email")?>">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter a strong password" name="userPassword">
  </div>
  <div class="form-group">
    <label for="exampleInputUsername1">Username</label>
    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter your display name" name="userName" value="<?php echo $this->request->getPost("userName")?>">
  </div>
  <button type="submit" class="btn btn-dark">Submit</button>
</form>

<?php echo $this->tag->endForm(); ?>

<br><br>
<p>
  Already have an account? <?php echo $this->tag->linkTo(["users/login", "Login here."]) ?>
</p>
