<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Order History - Details
    </h1>
</div>

<?php echo $this->getContent() ?>

<?php
    $order = Orders::findFirstByid($this->request->getPost('orderId'));

    $order_details = explode("|",$order->details);

    echo "<div class=\"alert alert-dark\">";
    echo "<h5>Order ID: #" . $order->id . "</h5>";
    echo "<h5>Date of purchase: " . $order->purchase_date . "</h5>";
    if ($order->book_date == "0000-00-00") {
        echo "<h5>Booked collection date: (no date set)</h5>"; 
    } else {
        echo "<h5>Booked collection date: " . $order->book_date . "</h5>"; 
    }
    echo "</div>";

    echo "<table class=\"table table-hover\">";
    echo "<thead class=\"thead-dark\">";
    echo "<tr>";
    echo "<th scope=\"col\">Product</th>";
    echo "<th scope=\"col\">Name</th>";
    echo "<th scope=\"col\">Quantity</th>";
    echo "<th scope=\"col\">Total</th>";
    echo "</tr>";
    echo "</thead>";
    echo "<tbody>";

    foreach ($order_details as $details) {
        if (strlen($details) <= 0) {
            continue;
        }

        $item = explode("{", $details);

        echo "<tr>";
        echo "<td>" . $item[0] . "</td>";
        echo "<td>" . $item[1] . "</td>";
        echo "<td>" . $item[2] . "</td>";
        echo "<td>$" . number_format((float)($item[3]), 2, '.', '') . "</td>";
        echo "</tr>";
    }
    if ($order->discount) {
        echo "<tr>";
        echo "<th scope=\"row\">Discount:</th>";
        echo "<td></td>";
        //echo "<td>" . (100 - ($this->session->get('discount_rate') * 100)) . "%</td>";
        echo "<td></td>";
        echo "<td><strong>-$" . number_format((float)$order->discount, 2, '.', '') . "</strong></td>";
        echo "</tr>";
    }

    echo "<tr>";
    echo "<th scope=\"row\">Total cost (BND):</th>";
    echo "<td></td>";
    echo "<td></td>";
    echo "<td><strong>$" . number_format((float)($order->total_cost - $order->discount), 2, '.', '') . "</strong></td>";
    echo "</tr>";
    echo "</tbody>";
    echo "</table>";

    echo "<div class=\"text-center mx-auto\">";
    echo "<a type=\"button\" href=\"http://localhost:8000/users/orderhistory\" class=\"btn btn-info btn-lg text-center mx-auto\">Back</a>";
    echo "</div>";

    echo "<br>";
?>

<br>
