<div align="center" id="checkedout">
    <div class="sub-content">
        <h3><strong>Inquiry Submitted</strong></h3>
        <br>
        We have received your venue booking inquiry and will contact you shortly, thank you.
        <br>
        <br>
        You can click the button below to return to the homepage or navigate to another page using the navbar above.
        <br>
        <br>
    </div>
    <div class="text-center mx-auto">
    <button type="button" class="btn btn-dark text-center mx-auto"><?php echo $this->tag->linkTo(["index", "HOME", "style" => "text-decoration: none; color: #FFFFFF"]); ?></button>
</div>
</div>