<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>DotRoot Tutorial</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand"><?php echo $this->tag->linkTo(["", "HOME", "style" => "text-decoration: none; color: #FFFFFF;"]) ?></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse px-2" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item px-2 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Plan Your Days
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Opening Hours</a>
                            <a class="dropdown-item" href="#">Park Maps</a>
                            <a class="dropdown-item" href="#">JP Directions</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Park Policies</a>
                            <a class="dropdown-item" href="#">FAQ</a>
                        </div>
                    </li>
                    <li class="nav-item px-2 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Things To Do
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Things To Do</a>
                        <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Playground</a>
                            <a class="dropdown-item" href="#">Events</a>
                            <a class="dropdown-item" href="#">Food Court</a>
                            <a class="dropdown-item" href="http://localhost:8000/tickets">Tickets</a>
                            <a class="dropdown-item" href="http://localhost:8000/merchandise">Merchandise</a>
                        </div>
                    </li>
                    <li class="nav-item px-2">
                        <a class="nav-link" href="http://localhost:8000/venuebooking">Venue Booking</a>
                    </li>
                    <li class="nav-item px-2">
                        <a class="nav-link" href="#">Careers</a>
                    </li>
                    <li class="nav-item px-2">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <?php 
                    if ($this->session->has('auth')) {?>
                        <li class="nav-item mx-3">
                        <a class="d-flex align-items-center nav-link" href="http://localhost:8000/cart">Cart</a>
                        </li>
                        <li class="nav-item px-2 dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #FFFFFF;">
                            <?php echo htmlspecialchars($this->session->get('user')->username) ?>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="http://localhost:8000/users/account">Manage Account</a>
                            <a class="dropdown-item" href="http://localhost:8000/tickets">Purchase Tickets</a>
                            <a class="dropdown-item" href="http://localhost:8000/merchandise">Purchase Merchandise</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="http://localhost:8000/session/end" style="color: #fb3f00 !important">Logout</a>
                        </div>
                        </li>
                        <?php
                    } else {
                        echo "<a type=\"button\" href=\"http://localhost:8000/users/login\" class=\"btn btn-dark text-center mx-auto\">Login</a>";
                    }?>
                </ul>
            </div>
        </nav>
        <div>
            <br>
            <br>
            <div class="container">
                <?php echo $this->getContent(); ?>
            </div>
        </div>
        <!-- comment -->
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
